/* eslint-disable */
const CONSTANTS = {};

CONSTANTS.LINK_DASHBOARD = "/dashboard";
CONSTANTS.LINK_ASSOCIATE_UNIT = "/dashboard/associate-unit";
CONSTANTS.LINK_ASSIGN_UNIT = "/dashboard/assign-unit";
CONSTANTS.LINK_MOVEMENTS = "/dashboard/reports/movements";
CONSTANTS.LINK_DEVICE_PROCESS = "/dashboard/device-process";
CONSTANTS.LINK_FATED_WASTED = "/dashboard/reports/fated";
CONSTANTS.LINK_NOTIFICATIONS = "/dashboard/reports/notifications";
CONSTANTS.LINK_HEALTH_AUTHORITY = "/dashboard/manage/health-authority";
CONSTANTS.LINK_LOCATION = "/dashboard/manage/location";
CONSTANTS.LINK_PRODUCT = "/dashboard/manage/product";
CONSTANTS.LINK_MANAGE_STOCK = "/dashboard/manage/manage-stock";
CONSTANTS.LINK_ALERTS_WARNINGS = "/dashboard/manage/alerts-warnings";
CONSTANTS.LINK_DERESERVATIONED = "/dashboard/reports/dereservationed";
CONSTANTS.LINK_ASSIGNED = "/dashboard/reports/assigned";
CONSTANTS.LINK_STOCK = "/dashboard/reports/stock";
CONSTANTS.LINK_HOSPITAL = "/dashboard/manage/hospital";
CONSTANTS.LINK_DEVICE = "/dashboard/manage/device";
CONSTANTS.LINK_USER = "/dashboard/manage/user";
CONSTANTS.LINK_MANAGE_MOVEMENT = "/dashboard/manage/movement";
CONSTANTS.LINK_SETTINGS = "/dashboard/settings";
CONSTANTS.LINK_MANAGE_RULE = "/dashboard/manage/rule";

CONSTANTS.NAME = "Name";
CONSTANTS.CODE = "Code";
CONSTANTS.NAME_DASHBOARD = "Dashboard";
CONSTANTS.NAME_ASSOCIATE_UNIT = "Associate Units";
CONSTANTS.NAME_ASSIGN_UNIT = "Assign Unit";
CONSTANTS.NAME_REPORTS = "Reports";
CONSTANTS.NAME_MOVEMENTS = "Movement";
CONSTANTS.NAME_MOVEMENTSS = "Movements";
CONSTANTS.NAME_REMOVED = "Removed";
CONSTANTS.NAME_DERESERVATIONED = "Dereservation";
CONSTANTS.NAME_DERESERVATIONS = "Dereservations";
CONSTANTS.NAME_STOCK = "Stock";
CONSTANTS.NAME_STOCKS = "Stocks";
CONSTANTS.NAME_ASSIGNED = "Assigned";
CONSTANTS.NAME_MANAGE = "Manage";
CONSTANTS.NAME_HOSPITAL = "Hospital";
CONSTANTS.NAME_HOSPITALS = "Hospitals";
CONSTANTS.NAME_DEVICE = "Device";
CONSTANTS.NAME_DEVICES = "Devices";
CONSTANTS.NAME_LOCATION = "Location";
CONSTANTS.LABELS_LOCATION = "Location";
CONSTANTS.NAME_LOCATIONS = "Locations";
CONSTANTS.NAME_USER = "User";
CONSTANTS.NAME_USERS = "Users";
CONSTANTS.NAME_MANAGE_MOVEMENT = "Movement";
CONSTANTS.NAME_MANAGE_MOVEMENTS = "Movements";
CONSTANTS.NAME_SETTINGS = "Settings";
CONSTANTS.NAME_RESET = "Reset";
CONSTANTS.NAME_APPLY = "Apply";
CONSTANTS.NAME_ADD = "Add";
CONSTANTS.NAME_ALERTS_WARNINGS = "Alerts & Warnings";
CONSTANTS.NAME_PRODUCT = "Product";
CONSTANTS.NAME_PRODUCTS = "Products";
CONSTANTS.NAME_HEALTH_AUTHORITY = "Health Authority";
CONSTANTS.NAME_HEALTH_AUTHORITIES = "Health Authorities";
CONSTANTS.NAME_FILTER = "Filter";
CONSTANTS.NAME_DEVICE_PROCESS = "Device Process";
CONSTANTS.NAME_FATED_WASTED = "Fated";
CONSTANTS.NAME_NOTIFICATIONS = "Notifications";
CONSTANTS.NAME_DESCRIPTION = "Description";
CONSTANTS.NAME_TYPE = "Type";
CONSTANTS.NAME_MANAGE_RULE = "Rule";
CONSTANTS.NAME_RULES = "Rules";

// reducers
CONSTANTS.USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
CONSTANTS.USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
CONSTANTS.USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
CONSTANTS.USER_IS_LOGGEDIN = "USER_IS_LOGGEDIN";
CONSTANTS.USER_LOGOUT = "USER_LOGOUT";

CONSTANTS.GET_FORM_TABLE_DATA_REQUEST = "GET_FORM_TABLE_DATA_REQUEST";
CONSTANTS.GET_FORM_TABLE_DATA_SUCCESS = "GET_FORM_TABLE_DATA_SUCCESS";
CONSTANTS.GET_FORM_TABLE_DATA_FAIL = "GET_FORM_TABLE_DATA_FAIL";

CONSTANTS.GET_DEVICE_REQUEST = "GET_DEVICE_REQUEST";
CONSTANTS.GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
CONSTANTS.GET_DEVICE_FAIL = "GET_DEVICE_FAIL";

CONSTANTS.ADD_DEVICE_REQUEST = "ADD_DEVICE_REQUEST";
CONSTANTS.ADD_DEVICE_SUCCESS = "ADD_DEVICE_SUCCESS";
CONSTANTS.ADD_DEVICE_FAIL = "ADD_DEVICE_FAIL";

CONSTANTS.UPDATE_DEVICE_REQUEST = "UPDATE_DEVICE_REQUEST";
CONSTANTS.UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
CONSTANTS.UPDATE_DEVICE_FAIL = "UPDATE_DEVICE_FAIL";

CONSTANTS.DELETE_DEVICE_REQUEST = "DELETE_DEVICE_REQUEST";
CONSTANTS.DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
CONSTANTS.DELETE_DEVICE_FAIL = "DELETE_DEVICE_FAIL";

CONSTANTS.GET_DEVICETYPE_REQUEST = "GET_DEVICETYPE_REQUEST";
CONSTANTS.GET_DEVICETYPE_SUCCESS = "GET_DEVICETYPE_SUCCESS";
CONSTANTS.GET_DEVICETYPE_FAIL = "GET_DEVICETYPE_FAIL";

CONSTANTS.GET_LOCATIONTYPE_REQUEST = "GET_LOCATIONTYPE_REQUEST";
CONSTANTS.GET_LOCATIONTYPE_SUCCESS = "GET_LOCATIONTYPE_SUCCESS";
CONSTANTS.GET_LOCATIONTYPE_FAIL = "GET_LOCATIONTYPE_FAIL";

CONSTANTS.GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST";
CONSTANTS.GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
CONSTANTS.GET_CLIENT_FAIL = "GET_CLIENT_FAIL";

CONSTANTS.GET_LOCATION_TYPE_REQUEST = "GET_LOCATION_TYPE_REQUEST";
CONSTANTS.GET_LOCATION_TYPE_SUCCESS = "GET_LOCATION_TYPE_SUCCESS";
CONSTANTS.GET_LOCATION_TYPE_FAIL = "GET_LOCATION_TYPE_FAIL";

CONSTANTS.GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
CONSTANTS.GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
CONSTANTS.GET_LOCATION_FAIL = "GET_LOCATION_FAIL";

CONSTANTS.ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
CONSTANTS.ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
CONSTANTS.ADD_LOCATION_FAIL = "ADD_LOCATION_FAIL";

CONSTANTS.UPDATE_LOCATION_REQUEST = "UPDATE_LOCATION_REQUEST";
CONSTANTS.UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
CONSTANTS.UPDATE_LOCATION_FAIL = "UPDATE_LOCATION_FAIL";

CONSTANTS.DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
CONSTANTS.DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
CONSTANTS.DELETE_LOCATION_FAIL = "DELETE_LOCATION_FAIL";

CONSTANTS.SET_API_RESPONSE_TYPE = "SET_API_RESPONSE_TYPE";
CONSTANTS.SET_ROUTE_TYPE = "SET_ROUTE_TYPE";
CONSTANTS.SET_THEME_COLOR = "SET_THEME_COLOR";

CONSTANTS.GET_SCREEN_REQUEST = "GET_SCREEN_REQUEST";
CONSTANTS.GET_SCREEN_SUCCESS = "GET_SCREEN_SUCCESS";
CONSTANTS.GET_SCREEN_FAIL = "GET_SCREEN_FAIL";

CONSTANTS.SET_DATE_FORMAT = "SET_DATE_FORMAT";

CONSTANTS.GET_FILTER_CRITERIA_REQUEST = "GET_FILTER_CRITERIA_REQUEST";
CONSTANTS.FILTER_CRITERIA_REQUEST_SUCCESS = "FILTER_CRITERIA_REQUEST_SUCCESS";
CONSTANTS.FILTER_CRITERIA_REQUEST_ERROR = "FILTER_CRITERIA_REQUEST_ERROR";

CONSTANTS.GET_DATA_REQUEST = "GET_DATA_REQUEST";
CONSTANTS.GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
CONSTANTS.GET_DATA_ERROR = "GET_DATA_ERROR";
CONSTANTS.CLEAR_DATA = "CLEAR_DATA";
CONSTANTS.CLEAR_FILTER_CRITERIA = "CLEAR_FILTER_CRITERIA";

CONSTANTS.UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
CONSTANTS.UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
CONSTANTS.UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL";

CONSTANTS.DELETE_ROW_REQUEST = "DELETE_ROW_REQUEST";
CONSTANTS.DELETE_ROW_SUCCESS = "DELETE_ROW_SUCCESS";
CONSTANTS.DELETE_ROW_FAIL = "DELETE_ROW_FAIL";

CONSTANTS.GET_USER_GROUPS_REQUEST = "GET_USER_GROUPS_REQUEST";
CONSTANTS.GET_USER_GROUPS_SUCCESS = "GET_USER_GROUPS_SUCCESS";
CONSTANTS.GET_USER_GROUPS_FAIL = "GET_USER_GROUPS_FAIL";

CONSTANTS.GET_DEVICE_TYPE_REQUEST = "GET_DEVICE_TYPE_REQUEST";
CONSTANTS.GET_DEVICE_TYPE_SUCCESS = "GET_DEVICE_TYPE_SUCCESS";
CONSTANTS.GET_DEVICE_TYPE_FAIL = "GET_DEVICE_TYPE_FAIL";

CONSTANTS.GET_CLIENT_ID_REQUST = "GET_CLIENT_ID_REQUST";
CONSTANTS.GET_CLIENT_ID_SUCCESS = "GET_CLIENT_ID_SUCCESS";
CONSTANTS.GET_CLIENT_ID_FAIL = "GET_CLIENT_ID_FAIL";

CONSTANTS.GET_DOWNLOAD_DATA_REQUEST = "GET_DOWNLOAD_DATA_REQUEST";
CONSTANTS.GET_DOWNLOAD_DATA_SUCCESS = "GET_DOWNLOAD_DATA_SUCCESS";
CONSTANTS.GET_DOWNLOAD_DATA_FAIL = "GET_DOWNLOAD_DATA_FAIL";

CONSTANTS.UNMOUNT_DISPLAY_CONFIG_DATA = "UNMOUNT_DISPLAY_CONFIG_DATA";

CONSTANTS.UPLOAD_EXCEL_FILE_REQUEST = "UPLOAD_EXCEL_FILE_REQUEST";
CONSTANTS.UPLOAD_EXCEL_FILE_SUCCESS = "UPLOAD_EXCEL_FILE_SUCCESS";
CONSTANTS.UPLOAD_EXCEL_FILE_FAIL = "UPLOAD_EXCEL_FILE_FAIL";

CONSTANTS.POST_DATA_REQUEST = "POST_DATA_REQUEST";
CONSTANTS.POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
CONSTANTS.POST_DATA_ERROR = "POST_DATA_ERROR";

CONSTANTS.GET_DRAWER_REQUEST = "GET_DRAWER_REQUEST";
CONSTANTS.GET_DRAWER_SUCCESS = "GET_DRAWER_SUCCESS";
CONSTANTS.GET_DRAWER_FAIL = "GET_DRAWER_FAIL";

//labels
CONSTANTS.USERNAME = "Username";
CONSTANTS.PASSWORD = "Password";
CONSTANTS.SECURE_LOGIN = "Secure Login";
CONSTANTS.EMAIL = "Email";
CONSTANTS.OTP = "OTP";

//other_strings
CONSTANTS.STRINGS_ADMIN = "ADMIN";
CONSTANTS.STRINGS_FORGOTPASSWORD = "Forgot Password ?";
CONSTANTS.STRINGS_SIGNIN = "Sign In";
CONSTANTS.STRINGS_BACK = "BACK";
CONSTANTS.STRINGS_COPYRIGHT = "Copyright © ";
CONSTANTS.STRINGS_SPACECODE_SAS = "Spacecode Healthcare S.A. ";
CONSTANTS.STRINGS_ALLRIGHTSRESERVED = "All rights reserved. ";
CONSTANTS.STRINGS_FORGOTYOURPASS = "Forgot Your Password?";
CONSTANTS.STRINGS_OTPLOGIN = "Login via OTP";
CONSTANTS.STRINGS_OTPLOGIN_SUBHEADING =
  "Please enter the OTP, which you have received in your registered email.";
CONSTANTS.STRINGS_FORGOTPASS_SUBHEADING =
  "Don't worry. Recovering the password is easy. Just tell us the email address you have registered with BloodSpace.";

CONSTANTS.NEXT = "Next";
CONSTANTS.NEXT_RECORD = "Next Record";
CONSTANTS.COMPLETE = "Complete";
CONSTANTS.EDIT = "Edit";
CONSTANTS.LABELS_DEVICE_TYPE = "Device Type";
CONSTANTS.LABELS_CLIENT = "Hospital";

CONSTANTS.ADD_HOSPITAL = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_HOSPITAL;
CONSTANTS.ADD_USER = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_USER;
CONSTANTS.ADD_DEVICE = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_DEVICE;
CONSTANTS.ADD_MOVEMENT =
  CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_MANAGE_MOVEMENT;
CONSTANTS.ADD_RULE = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_MANAGE_RULE;
CONSTANTS.ADD_ALERTS_WARNINGS =
  CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_ALERTS_WARNINGS;
CONSTANTS.ADD_LOCATION = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_LOCATION;
CONSTANTS.ADD_PRODUCT = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_PRODUCT;
CONSTANTS.ADD_STOCK = CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_STOCK;
CONSTANTS.ADD_HEALTH_AUTHORITY =
  CONSTANTS.NAME_ADD + " " + CONSTANTS.NAME_HEALTH_AUTHORITY;
CONSTANTS.IS_INVALID = "is invalid.";
CONSTANTS.IS_INVALID_PHONE =
  CONSTANTS.IS_INVALID +
  " " +
  "(only numbers are allowed. For ex. (020) 1234 5678)";
CONSTANTS.ERROR_PASSWORD =
  "Minimum eight characters, at least one uppercase ,lowercase letter , a number and a special character";

//Validation_errors
CONSTANTS.ERROR_USERNAMES = "You must provide a username.";
CONSTANTS.ERROR_PASSWORD = "You must provide a password.";

//add_hospital_labels
CONSTANTS.LABEL_HOSPITAL_NAME = "Hospital Name";
CONSTANTS.LABEL_HOSPITAL_CODE = "Hospital Code";
CONSTANTS.LABEL_ADDRESS = "Address";
CONSTANTS.LABEL_ADDRESS1 = "Address Line 1";
CONSTANTS.LABEL_ADDRESS2 = "Address Line 2";
CONSTANTS.LABEL_CITY = "City";
CONSTANTS.LABEL_STATE = "State";
CONSTANTS.LABEL_ZIPCODE = "Zip Code";
CONSTANTS.LABEL_PHONE = "Phone";
CONSTANTS.LABEL_UPLOAD_IMAGE = "Upload Image";
//confirmationDialog
CONSTANTS.LABEL_ARE_YOU_SURE =
  "Are you sure you want to deactivate this record?";
CONSTANTS.LABEL_SUSPEND_USER = "Suspend User Period";
CONSTANTS.LABEL_COMMENT = "Comments";

//add_location_labels
CONSTANTS.LABEL_LOCATION_NAME = CONSTANTS.NAME_LOCATION + " " + CONSTANTS.NAME;
CONSTANTS.LABEL_LOCATION_CODE = CONSTANTS.NAME_LOCATION + " " + CONSTANTS.CODE;
CONSTANTS.LABEL_LOCATION_TYPE =
  CONSTANTS.NAME_LOCATION + " " + CONSTANTS.NAME_TYPE;

//add_device_labels
CONSTANTS.LABEL_LOCATION = "Location";
CONSTANTS.LABEL_CLIENT = "Hospital";
CONSTANTS.LABEL_SERIAL_NUMBER = "Serial Number";
(CONSTANTS.LABEL_IP_ADDRESS = "IP Address"),
  (CONSTANTS.LABEL_DEVICE_TYPE = "Device Type");

//add_user_labels
CONSTANTS.LABEL_FIRST_NAME = "First Name";
CONSTANTS.LABEL_LAST_NAME = "Last Name";
CONSTANTS.LABEL_BADGE_ID = "Badge ID";
CONSTANTS.LABEL_USER_GROUP = "User Group";
CONSTANTS.LABEL_DESIGNATION = "Designation";
//add_stock_labels
CONSTANTS.LABEL_HEADER_1 = "Header 1";
CONSTANTS.LABEL_HEADER_2 = "Header 2";
CONSTANTS.LABEL_HEADER_3 = "Header 3";
CONSTANTS.LABEL_HEADER_4 = "Header 4";
CONSTANTS.LABEL_HEADER_5 = "Header 5";
CONSTANTS.LABEL_HEADER_6 = "Header 6";
CONSTANTS.LABEL_STATUS = "Status";
CONSTANTS.LABEL_SAMPLE_DATA = "Sample Excel Data :";
CONSTANTS.IS_EMPTY = "It's Empty Here";
CONSTANTS.IS_EMPTY_SUBHEADING = "Looks like this page can't be found.";

//Validation_errors
CONSTANTS.IS_REQUIRED = " is required";
CONSTANTS.ERROR_USERNAMES = CONSTANTS.USERNAME + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_PASSWORD = CONSTANTS.PASSWORD + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HOSPITAL_NAME =
  CONSTANTS.LABEL_HOSPITAL_NAME + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HOSPITAL_CODE =
  CONSTANTS.LABEL_HOSPITAL_CODE + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ADDRESS = CONSTANTS.LABEL_ADDRESS + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ADDRESS_1 = CONSTANTS.LABEL_ADDRESS1 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ADDRESS_2 = CONSTANTS.LABEL_ADDRESS2 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_CITY = CONSTANTS.LABEL_CITY + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_STATE = CONSTANTS.LABEL_STATE + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ZIPCODE = CONSTANTS.LABEL_ZIPCODE + " " + CONSTANTS.IS_INVALID;
CONSTANTS.ERROR_PHONE =
  CONSTANTS.LABEL_PHONE + " " + CONSTANTS.IS_INVALID_PHONE;
CONSTANTS.ERROR_LOCATION_ID =
  CONSTANTS.LABEL_LOCATION_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_CLIENT_ID = CONSTANTS.LABEL_CLIENT_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_SERIAL_NUMBER =
  CONSTANTS.LABEL_SERIAL_NUMBER + CONSTANTS.IS_REQUIRED;

CONSTANTS.ERROR_DEVICE_TYPE_ID =
  CONSTANTS.LABEL_DEVICE_TYPE_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_FIRST_NAME = CONSTANTS.LABEL_FIRST_NAME + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_LAST_NAME = CONSTANTS.LABEL_LAST_NAME + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_BADGE_ID = CONSTANTS.LABEL_BADGE_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_DESIGNATION =
  CONSTANTS.LABEL_DESIGNATION + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ROLE_ID = CONSTANTS.LABEL_ROLE_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_USER_GROUP_ID =
  CONSTANTS.LABEL_USER_GROUP_ID + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_LOCATION_NAME =
  CONSTANTS.LABEL_LOCATION_NAME + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_LOCATION_CODE =
  CONSTANTS.LABEL_LOCATION_CODE + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_DESCRIPTION =
  CONSTANTS.NAME_DESCRIPTION + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_LOCATION_TYPE =
  CONSTANTS.LABEL_LOCATION_TYPE + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_ADDED_BY = CONSTANTS.LABEL_ADDED_BY + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_1 = CONSTANTS.LABEL_HEADER_1 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_2 = CONSTANTS.LABEL_HEADER_2 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_3 = CONSTANTS.LABEL_HEADER_3 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_4 = CONSTANTS.LABEL_HEADER_4 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_5 = CONSTANTS.LABEL_HEADER_5 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HEADER_6 = CONSTANTS.LABEL_HEADER_6 + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_STATUS = CONSTANTS.LABEL_STATUS + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_HOSPITALS = CONSTANTS.NAME_HOSPITALS + CONSTANTS.IS_REQUIRED;
CONSTANTS.ERROR_UNIT_ID =
  "Invalid Unit ID, Length should be minimum 13 charecters";
CONSTANTS.ERROR_UNIT_ID_MATCH = "Enter a valid Unit ID";
CONSTANTS.ERROR_IP_ADDRESS = "IP address is invalid";
CONSTANTS.ERROR_SUSPEND_USER = "Invalid! , Only numbers are allowed";

//buttons
CONSTANTS.LOGIN_BUTTON = "Login";
CONSTANTS.LOGIN_OTPBUTTON = "Login via OTP";
CONSTANTS.SEND_BUTTON = "Send";
CONSTANTS.EXPORT = "Export";
CONSTANTS.SAVE_OR_ADD = "Save/Add";
CONSTANTS.ADD = "Add";
CONSTANTS.CANCEL = "Cancel";
CONSTANTS.CONTINUE = "Continue";
CONSTANTS.SAVE = "Save";
CONSTANTS.ADD_NEW_RECIPIENT = "Add New Recipient";

CONSTANTS.UNDERSTOOD = "Understood";
CONSTANTS.BACK = "Back";
CONSTANTS.ASSIGN = "Assign";
(CONSTANTS.NEXT = "Next"), (CONSTANTS.COMPLETE = "Complete");

CONSTANTS.FIRST_NAME = "First Name";
CONSTANTS.LAST_NAME = "Last Name";
CONSTANTS.BLOOD_GROUP = "Blood Group";
CONSTANTS.DOB = "Date Of Birth";
CONSTANTS.RECIPIENT_ID = "Recipient ID";
CONSTANTS.MALE = "Male";
CONSTANTS.FEMALE = "Female";
CONSTANTS.GENDER = "Gender";
CONSTANTS.PLAC_HOLDER_ASSIGN_UI = "Recipient Name / MRN / Unit ID";
CONSTANTS.SHOWING = "Showing";
CONSTANTS.RESULTS = "results";
CONSTANTS.ADD_NEW_RECIPIENT = "Add New Recipient";
CONSTANTS.EMERGENCY_STOCK_ASSIGN = "Emergency Stock Assign";
CONSTANTS.NOT_FOUND = "Not Found";
CONSTANTS.COMMENTS = "Comments";
CONSTANTS.COMMENTS_PLACE_HOLDER = "Comments will be here";
CONSTANTS.UNITS = "Units";
CONSTANTS.ARE_YOU_SURE_WANT_TO_ASSIGN = "Are you sure you want to assign";
CONSTANTS.EMERGENCY_ASSIGN = " The units are getting assigned for emergency";
CONSTANTS.UNIT_NOT_AVAILABLE = "Unit Not Available";
CONSTANTS.UNIT = "UNIT";
CONSTANTS.HAS_ALREADY_ASSIGNED = "has already been assigned to another patient";
CONSTANTS.SAME_DERESERVATION_DATE = "Same dereservation data and time for all.";
CONSTANTS.SAME_DEVICE = "Same device for all.";
CONSTANTS.DERESERVATION_DATE = "Dereservation Date";
CONSTANTS.PRODUCT_CODE = "Product Code";
CONSTANTS.UNIT_ID_NUMBER = "Unit ID";
CONSTANTS.PLEASE_SCAN_BAR_CODE_OR_ENTER_MANUALLY =
  "Please scan Unit ID Barcode(s) or enter data manually";
CONSTANTS.INVALID = "Invalid";
CONSTANTS.INVALID_RECIPIENT_ID = "Invalid Recipient ID";
CONSTANTS.INVALID_FIRST_NAME = "Invalid First Name";
CONSTANTS.INVALID_LAST_NAME = "Invalid Last Name";
CONSTANTS.SELECT_BLOOD_GROUP = "Please select Blood Group";
CONSTANTS.UNIT_ID = "Unit Id *";
CONSTANTS.UNIT_ID_FILTER = "Unit Id";

CONSTANTS.ACTIONS = "Actions";
CONSTANTS.ROWS_PER_PAGE = "Rows Per Page";
CONSTANTS.RESULT = "Result";
CONSTANTS.INCORRECT_ENTRY = "Incorrect entry.";
CONSTANTS.DIALOG_UNIT_TEXT = "Unit";
CONSTANTS.STATIC = "Static";
CONSTANTS.LIVE = "Live";
CONSTANTS.LABEL_APPLICATION_BEHAVIOR = "Application Behavior :";
CONSTANTS.LABEL_DATE_FORMATS = "Date Formats";
CONSTANTS.LABEL_DATE_FORMAT_ONE = "MMM-DD-YYYY HH:mm a";
CONSTANTS.LABEL_DATE_FORMAT_TWO = "MM-DD-YYYY HH:mm a";
CONSTANTS.LABEL_DATE_FORMAT_THREE = "DD-MMM-YYYY HH:mm a";
CONSTANTS.LABEL_DATE_FORMAT_FOUR = "DD-MM-YYYY HH:mm a";

//add_hospital_labels
CONSTANTS.LABEL_NAME = "Hospital Name";
CONSTANTS.LABEL_CODE = "Hospital Code";
CONSTANTS.LABEL_ADDRESS1 = "Address Line 1";
CONSTANTS.LABEL_ADDRESS2 = "Address Line 2";
CONSTANTS.LABEL_CITY = "City";
CONSTANTS.LABEL_STATE = "State";
CONSTANTS.LABEL_ZIPCODE = "Zip Code";
CONSTANTS.LABEL_UPLOAD_IMAGE = "Upload Image";

// pre-endcoded form
CONSTANTS.LABEL_PRODUCTCODE = "Product Code *";
CONSTANTS.LABEL_DONATIONID = "Unit ID *";
CONSTANTS.LABEL_BLOODGROUP = "Blood Group(ABO/RH) *";
CONSTANTS.LABEL_DIMENSION = "Dimensions";
CONSTANTS.LABEL_EXPIRYDATE = "Expiry Date and Time *";
CONSTANTS.LABEL_COLLECTIONDATE = "Collection Date and Time";
CONSTANTS.LABEL_SPECIALTESTING = "Special Testing ";
CONSTANTS.LABEL_CHECK = "Check";
CONSTANTS.LABEL_SEARCHHOSPITAL = "Select Hospital";
CONSTANTS.LABEL_LOCATION = "Location";
CONSTANTS.LABEL_STORAGE = "Storage";
CONSTANTS.LABEL_SINGLEVIEW = "Single View";
CONSTANTS.LABEL_LISTVIEW = "List View";
CONSTANTS.LABEL_BULKVIEW = "Bulk View";
CONSTANTS.LABEL_UNITON = " Units on Device";
CONSTANTS.LABEL_OF = "of ";
CONSTANTS.LABEL_OR = "Or ";
CONSTANTS.LABEL_ASSOCIATEUNITS = "Associate unit";
CONSTANTS.LABEL_TIPS = "TIPS";
CONSTANTS.LABEL_SINGLEVIEWTEXT =
  " You can view unit one by one and are able to save individually as you navigate the through arrows";
CONSTANTS.LABEL_LISTVIEWTEXT =
  " You can select one or multiple units from the list and save them to the database";
(CONSTANTS.LABEL_REQUIREDFIELD = " * indicates a required field"),
  (CONSTANTS.LABEL_PLEASE = "Please ");
CONSTANTS.LABEL_SCAN = "Scan ";
CONSTANTS.LABEL_THE = "The ";
CONSTANTS.LABEL_BARCODE = "Barcode ";
CONSTANTS.LABEL_AUTOMATICALLY = " that the fields are completed automatically.";
CONSTANTS.LABEL_YOUCANALSO = " You can also use";
CONSTANTS.LABEL_INPUT = "input ";
CONSTANTS.LABEL_THEM = "them ";
CONSTANTS.LABEL_MANUALLY = "manually ";
CONSTANTS.LABEl_FIELDS = "on the corresponding fields.";
CONSTANTS.LABEL_UNIT_ON_DEVICE = "Unit on Device";

//rfid reader

CONSTANTS.NAME_RFID_READER = "Connected to RFID reader ";
CONSTANTS.NAME_SPACECODE_NUMBER = " SPACECODE_DEVICE001";
CONSTANTS.LABEL_UNDER_CONSTRUCTION = "This page is under development";
CONSTANTS.LABEL_UNDER_LAST_UPDATE = "Last Updated IST: ";

//filtersLables
CONSTANTS.LABELS_USER_NAME = "User Name";
CONSTANTS.PLACE_HOLDER_SEARCH = "Search";
CONSTANTS.SPECIAL_TESTING = "Special Testing";
CONSTANTS.LABELS_ACTIVE = "Active";
CONSTANTS.LABELS_HOSPITAL_NUMBER = "Hospital Number";
CONSTANTS.LABELS_CARRIER_TYPE = "Carrier Type";
CONSTANTS.END_POINT = "End Point";
CONSTANTS.START_POINT = "Start Point";
CONSTANTS.CREATION_DATE = "Creation Date";
CONSTANTS.PRODUCTION_DATE = "Production Date";
CONSTANTS.EXPIRATION_DATE = "Expiration Date";
CONSTANTS.LABELS_WEIGHT = "Weight";
CONSTANTS.LABELS_COLLECTION_DATE = "Collection Date";
CONSTANTS.LABELS_INTERNAL_CODE = "Internal Code";
CONSTANTS.LABELS_RFID = "RFID";
CONSTANTS.DEVICE_SERIAL_NUMBER = "Device Serial Number";
CONSTANTS.DEVICE_LOCATION = "Device Location";
CONSTANTS.LOCATION_TYPE = "Location Type";
CONSTANTS.EXPIRY_DATE = "Expiry Date";
CONSTANTS.LABELS_PRODUCT_CODE = "Product Code";
CONSTANTS.LABEL_CITY = "City";
CONSTANTS.USER_ROLE = "User Role";
CONSTANTS.USER_GROUP = "User Group";

//colorConstants
CONSTANTS.COLOR_PRIMAY_MAIN = "#004372";
CONSTANTS.COLOR_PRIMAY_ICON = "#777777";
CONSTANTS.COLOR_SECONDARY_MAIN = "#ffffff";
CONSTANTS.COLOR_BACKGROUND_DEFAULT = "#f2f7fb";
CONSTANTS.COLOR_LIST_MAIN = "#D9E3EB";
CONSTANTS.COLOR_LABEL_MAIN = "#777777";

CONSTANTS.COLOR_DARK_GRAY = "#ACACAC";
CONSTANTS.COLOR_GRAY = "#777777";
CONSTANTS.COLOR_WHITE = "#ffffff";
CONSTANTS.COLOR_GREEN = "#31902D";
CONSTANTS.COLOR_GAMBOGE = "#da9100";
CONSTANTS.COLOR_RED = "#F50000";
CONSTANTS.COLOR_PERSIAN_BLUE = "#0B3FE4";
CONSTANTS.COLOR_HONEY_DEW = "#ECFAEC";
CONSTANTS.COLOR_SUNDOWN = "#FAA2A2";
CONSTANTS.COLOR_KHAKI = "#f7e98e";
CONSTANTS.COLOR_PERIWINKLE = "#B9C9FB";
CONSTANTS.COLOR_ALUMINIUM = "#8a8c8d";
CONSTANTS.COLOR_BLACK = "#000000";
CONSTANTS.COLOR_DIM_GRAY = "#676767";
CONSTANTS.COLOR_QUARTZ = "#DFE0EB";
CONSTANTS.COLOR_FREE_SPEECH_RED = "#BA1700";

CONSTANTS.BASEURL = "/api/v1/";

CONSTANTS.TITLE_PRIMARY = "Primary";
CONSTANTS.TITLE_MAGENTA = "Magenta";
CONSTANTS.TITLE_RED = "Red";
CONSTANTS.TITLE_GREEN = "Green";
CONSTANTS.TITLE_PURPLE = "Purple";
CONSTANTS.TITLE_DARK = "Dark";

//DataBase Table Constants
CONSTANTS.DEFAULT_VALUE = "Default Value";
CONSTANTS.VALIDATION_TYPE = "Validation Type";
CONSTANTS.REFERENCE = "Reference";
CONSTANTS.ALLOW_NULL = "Allow Null";
CONSTANTS.UNIQUE = "Unique";
CONSTANTS.REQUIRED = "Required";
CONSTANTS.INDEXED = "Indexed";
CONSTANTS.ACTION = "Action";
CONSTANTS.ADD_COLLECTIONS = "Add Collection";
CONSTANTS.SELECT_COLLECTIONS = "Select Collections";
CONSTANTS.SELECT_TYPE = "Select type";
CONSTANTS.SELECT_DATA_TYPE = "Select Data type";
CONSTANTS.TRUE = "True";
CONSTANTS.FALSE = "False";

//VOUCHER CONSTANTS

CONSTANTS.VOUCHER_DATA = "VOUCHER_DATA";
CONSTANTS.CLEAR_VOUCHER = "CLEAR_VOUCHER";

//dataBase Constants
CONSTANTS.LABEL = "Label";

export default CONSTANTS;
